<?php

namespace Proposal\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmRepository extends EntityRepository
{
}
