<?php

namespace Proposal\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Proposal1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Proposal1Repository extends EntityRepository
{
}
